# [Tue Jan  9 16:14:33 2018] 
# zshrc: toggle other zshrc files.

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

INCLUDE=/opt/chef/cookbooks/development-setup/files/zsh

source $INCLUDE/aliases
source $INCLUDE/oh-my-zsh
source $INCLUDE/ruby
source $INCLUDE/variables
# source $INCLUDE/moveme # left over from before
# source $INCLUDE/numpad

WORK_ZSHRC=~/projects/sandbox/zshrc 
if [ -f $WORK_ZSHRC ]; then
  source $WORK_ZSHRC
fi

