#WARNING! Your terminal appears to support fewer than 256 colors!
#If your terminal supports 256 colors, please export the appropriate environment variable
#_before_ loading this theme in your ~/.zshrc. In most terminal emulators, putting
#export TERM="xterm-256color" at the top of your ~/.zshrc is sufficient.
export TERM="xterm-256color"

clear

alias_prefixes=$(cat /opt/chef/cookbooks/development-setup/files/zsh/aliases.zsh | grep -o "^alias [^\-]*-.*=" | cut -d' ' -f2 | cut -d'-' -f1 | sort | uniq | xargs)
 echo "
   Ctrl-H: Home              ranger
   Ctrl-K: Up a directory    set -o vi # followed by ESC then:
                              '/' to reverse search shell history, or:
                                bindkey \"^R\" history-incremental-search-backward
                              'v' to edit.

  aliases:
  $alias_prefixes
"

# if screenfetch is here, call it first, discarded warnings
# which screenfetch >/dev/null 2>/dev/null && screenfetch 2>/dev/null
# shows apple logo and some stats

# end Splash page!!! ############

INCLUDE=/opt/chef/cookbooks/development-setup/files/zsh

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh


source $INCLUDE/oh-my-zsh.zsh

# Include this instead when using .oh-my-zsh/custom
source $INCLUDE/sources.zsh


# Vi editing mode with visual mode.
bindkey -M vicmd v edit-command-line
# See:
# "/" vi-history-search-backward
# "?" vi-history-search-forward
# "n" vi-repeat-search
# "N" vi-rev-repeat-search
#

# TMU, this means that:
#   sessions append to global history, but only on exit, and do not replaced the history
#unsetopt inc_append_history
#setopt share_history
#setopt APPEND_HISTORY
# # # # #

# history per open terminal... why isn't this standard?
mkdir -p "${HOME}/.history.d"
#export HISTFILE="${HOME}/.history.d/history-"`uname -n`"-"`id -nu`"-"`tty|cut -c6-`
if ! [ -z "$CHF" ] ;  then
  export HISTFILE="${HOME}/.history.d/${CHF}"
#else
# export HISTFILE="${HOME}/.history.d/history-"`uname -n`"-"`id -nu`""`tty|sed 's/\//-/g'`
fi
