" [Wed Jan 10 15:57:36 2018]
" extracted source files in development-setup

source /opt/chef/cookbooks/development-setup/files/vim/rc/f_keys
source /opt/chef/cookbooks/development-setup/files/vim/rc/leaders
source /opt/chef/cookbooks/development-setup/files/vim/rc/sets
source /opt/chef/cookbooks/development-setup/files/vim/rc/misc
" source /opt/chef/cookbooks/development-setup/files/vim/rc/try_me

execute pathogen#infect()

syntax on
